name: test_bazarr_execution
on: workflow_dispatch

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      ROOT_DIRECTORY: .
      UI_DIRECTORY: ./frontend
      ASSET_DIRECTORY: ./__builds__
      FETCH_DEPTH: 15 # Should be enough
    steps:
      - name: Validate branch
        if: ${{ github.ref != 'refs/heads/development' }}
        run: |
          echo This action can only be run on development branch, not ${{ github.ref }}
          exit 1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
          ref: development

      - name: Setup Git
        run: |
          git config --global user.name "github-actions" &&
          git fetch --depth ${{ env.FETCH_DEPTH }} --tags

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '${{ env.UI_DIRECTORY }}/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: Install Global Tools
        run: npm install -g release-it auto-changelog

      - name: Install UI Dependencies
        run: npm install
        working-directory: ${{ env.UI_DIRECTORY }}

      - name: Build UI
        run: npm run build
        working-directory: ${{ env.UI_DIRECTORY }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r '${{ env.ROOT_DIRECTORY }}/requirements.txt'

      - name: Test Bazarr execution
        run: |
          bash '${{ env.ROOT_DIRECTORY }}/scripts/build_test.sh'
